version: '3.5'

services:

  david_server:
    container_name: raindrop
    image: dvdkwak/apache-php-mysqli:latest
    networks:
      - david_net
    volumes:
      - ./../../projects/raindrop/:/var/www/html/
    labels:
      - "traefik.http.routers.david_php.rule=Host(`raindrop.localhost`)"

networks:
  david_net:
    external: true
  default:
    external: true
    name: david_net